# Generated by Django 4.2 on 2024-05-22 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_profile_is_email_verified'),
    ]

    operations = [
    ]
