# Generated by Django 4.2 on 2024-05-22 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20240522_2154'),
    ]

    operations = [
    ]
